services:
  db:
    build: 
      context: ./MariaDB
      dockerfile: Dockerfile
    container_name: database
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./MariaDB/volumes:/var/lib/mysql
    hostname: eam_database
    networks:
      - net_eam_docker_parcial
    healthcheck:
      test: ["CMD", "mariadb", "-u", "root", "-pdfpedrazag31"]
      interval: 30s
      timeout: 10s
      retries: 5

  app-tests:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-tests
    depends_on:
      db:
        condition: service_healthy
    networks:
      - net_eam_docker_parcial
    command: ["./mvnw", "test"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - net_eam_docker_parcial
    command: ["./mvnw", "spring-boot:run"]

networks:
  net_eam_docker_parcial:
    driver: bridge
    name: net_eam_docker_parcial
